# Generated by Django 4.0.4 on 2022-06-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
